NVCEntityFramework/Controllers/CocheController.cs
using Microsoft.AspNetCore.Mvc;
using NVCEntityFramework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NVCEntityFramework.Controllers
{
    public class CocheController : Controller
    {
        private ICoche car;
        public CocheController(ICoche car)
        {
            this.car = car;
        }
        public IActionResult Index()
        {
            return View(this.car);
        }
        [HttpPost]
        public IActionResult Index(String accion)
        {
            if (accion.ToLower() == "acelerar")
            {
                this.car.Acelerar();
            }
            else
            {
                this.car.Frenar();
            }
            return View(this.car);
        }
    }
}

NVCEntityFramework/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using NVCEntityFramework.Models;
using NVCEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NVCEntityFramework.Controllers
{
    public class DoctoresController : Controller
    {
        RepositoryDoctores repo;
        public DoctoresController(RepositoryDoctores repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UpdateDoctoresEspecialidad()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }
        [HttpPost]
        public IActionResult UpdateDoctoresEspecialidad(int iddoctor,String esp)
        {
            this.repo.UpdateEspecialidad(iddoctor, esp);
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }

        public IActionResult UpdateSalarioEspecialidad()
        {
            ViewData["especialidades"] = this.repo.GetEspecialidades();
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }
        [HttpPost]
        public IActionResult UpdateSalarioEspecialidad(int salario,String esp)
        {
            this.repo.ModificarSalarioEspecialidad(salario, esp);
            List<Doctor> doctores = this.repo.GetDoctoresEspecialidad(esp);
            ViewData["especialidades"] = this.repo.GetEspecialidades();
            return View(doctores);
        }
    }
}

NVCEntityFramework/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using NVCEntityFramework.Models;
using NVCEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NVCEntityFramework.Controllers
{
    public class EmpleadoController : Controller
    {
        private RepositoryEmpleados repo;
        public EmpleadoController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            ViewData["oficios"] = this.repo.getOficios();
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }
        [HttpPost]
        public IActionResult Index(int incremento,String oficio)
        {
            ViewData["oficios"] = this.repo.getOficios();
            ViewData["seleccionado"] = oficio;
            List<Empleado> empleados = this.repo.GetEmpleadoOficio(oficio);
            this.repo.ModificarSalarios(incremento,oficio);
            return View(empleados);
        }
        public IActionResult EmpleadosDepartamentosLambda(int departamento)
        {
            ResumenDepartamento resumen = this.repo.GetResumenDepartamento(departamento);
            return View(resumen);
        }
    }
}

NVCEntityFramework/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using NVCEntityFramework.Models;
using NVCEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NVCEntityFramework.Controllers
{
    public class EnfermosController : Controller
    {
        private RepositoryEnfermos repo;
        public EnfermosController(RepositoryEnfermos repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }
        public IActionResult detalles(int inscripcion)
        {
            Enfermo enf = this.repo.BuscarEnfermo(inscripcion);
            return View(enf);
        }

        public IActionResult EnfermosGenero(String genero)
        {
            List<Genero> generos = this.repo.GetGeneros();
            ViewData["Generos"]=generos;
            if (genero != null)
            {
                List<Enfermo> enfermos = this.repo.GetEnfermosGenero(genero);
                return View(enfermos);
            }else return View();
        }

        public IActionResult EliminarEnfermo(int inscripcion)
        {
            this.repo.EliminarEnfermo(inscripcion);
            return RedirectToAction("Index");
        }

        public IActionResult InsertarEnfermo()
        {
            List<Genero> generos = this.repo.GetGeneros();
            return View(generos);
        }
        [HttpPost]
        public IActionResult InsertarEnfermo(Enfermo enf)
        {
            this.repo.InsertarEnfermo(enf.Inscripcion, enf.Apellido, enf.Direccion, enf.FechaNacimiento, enf.Genero, enf.NSS);
            return RedirectToAction("Index");
        }

        public IActionResult ModificarEnfermo(int inscripcion)
        {
            ViewData["generos"] = this.repo.GetGeneros();
            Enfermo enf = this.repo.BuscarEnfermo(inscripcion);
            return View(enf);
        }
        [HttpPost]
        public IActionResult ModificarEnfermo(Enfermo enf)
        {
            this.repo.ModificarEnfermo(enf.Inscripcion, enf.Apellido, enf.Direccion, enf.FechaNacimiento, enf.Genero, enf.NSS);
            return RedirectToAction("Index");
        }
    }
}

NVCEntityFramework/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Jumbotron Template · Bootstrap</title>

    
    <link href="~/css/jumbotron.css" rel="stylesheet" />

    <!-- Bootstrap core CSS -->
    @*<link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">*@
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @@media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Coche">Coche</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Departamentos">Departamentos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Hospital">Hospitales EF</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="ResumenPlantilla" asp-controller="Plantilla">Plantilla Resumen</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Enfermos">Enfermos EF</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Empleado">Incremento de Salario</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="EmpleadosDepartamentosLambda" asp-controller="Empleado">Buscador de departamentos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="UpdateDoctoresEspecialidad" asp-controller="Doctores">Modificar Doctor</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="UpdateSalarioEspecialidad" asp-controller="Doctores">Modificar salarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="EmpleadosHospital">Empleados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="TodosEmpleados">Todos los empleados</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main role="main">

        

        <div class="container">

            @RenderBody()

            <!-- Example row of columns -->
            

            <hr>

        </div> <!-- /container -->

    </main>

    <footer class="container">
        <p>&copy; Company 2017-2020</p>
    </footer>
    <script src="~/js/jquery-3.5.1.slim.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@
    @*<script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
        <script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>*@
</body>
</html>