NVCEntityFramework/Controllers/EmpleadosHospitalController.cs
using Microsoft.AspNetCore.Mvc;
using NVCEntityFramework.Models;
using NVCEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NVCEntityFramework.Controllers
{
    public class EmpleadosHospitalController : Controller
    {
        RepositoryEmpleadosHospital repo;
        public EmpleadosHospitalController(RepositoryEmpleadosHospital repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<EmpleadoHospital> empleados = this.repo.GetEmpleadoHospital();
            return View(empleados);
        }

        public IActionResult ProcedimientoEmpleadosHospital()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ProcedimientoEmpleadosHospital(int hospitalcod)
        {
            ProcedimientoEmpleadoHospital datos = this.repo.GetEmpleadoHospital(hospitalcod);
            return View(datos);
        }
    }
}

NVCEntityFramework/Views/EmpleadosHospital/Index.cshtml
@model List<EmpleadoHospital>

<h1>Empleados de los Hospitales</h1>
@Html.ActionLink("Buscador de empleados","ProcedimientoEmpleadosHospital","EmpleadosHospital")
<table class="table table-bordered table-dark">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Funcion</th>
            <th>Salario</th>
            <th>Hospital</th>
        </tr>
    </thead>
    <tbody>
        @foreach (EmpleadoHospital emple in Model)
        {
            <tr>
                <td>@emple.Apellido</td>
                <td>@emple.Funcion</td>
                <td>@emple.Salario</td>
                <td>@emple.Hospital</td>
            </tr>
        }
    </tbody>
</table>

NVCEntityFramework/Views/EmpleadosHospital/ProcedimientoEmpleadosHospital.cshtml
@model ProcedimientoEmpleadoHospital

<h1>Procedimientos OUT</h1>

<form method="post">
    <label>Código hospital:</label>
    <input type="number" name="hospitalcod" class="form-control" />
    <button type="submit" class="btn-light">Buscar empleados</button>
</form>

@if (Model != null)
{
    <h2>Suma Salarial: @Model.SumaSalarial</h2>
    <h2>Media Salarial: @Model.MediaSalarial</h2>
    <table class="table table-bordered table-light">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Funcion</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach(EmpleadoHospital emple in Model.empleados)
            {
                <tr>
                    <td>@emple.Apellido</td>
                    <td>@emple.Funcion</td>
                    <td>@emple.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}